---
- name: Append new Zabbix server IP to configuration
  hosts: all
  gather_facts: no
  vars:
    zabbix_conf_path: "C:\\Zabbix\\conf\\zabbix_agentd.win.conf"  # Replace with the actual path
    new_server_ip: "10.51.200.123"  # Replace with the new server IP

  tasks:
    - name: Read current Server line
      ansible.windows.win_shell: |
        Get-Content "{{ zabbix_conf_path }}" | Select-String "^Server\s*=" | ForEach-Object { $_.Line }
      register: current_server_line

    - name: Read current ServerActive line
      ansible.windows.win_shell: |
        Get-Content "{{ zabbix_conf_path }}" | Select-String "^ServerActive\s*=" | ForEach-Object { $_.Line }
      register: current_serveractive_line

    - name: Append new IP to Server line
      community.windows.win_lineinfile:
        path: "{{ zabbix_conf_path }}"
        regexp: '^Server\s*='
        line: "{{ current_server_line.stdout_lines[0] }},{{ new_server_ip }}"
        backrefs: yes

    - name: Append new IP to ServerActive line
      community.windows.win_lineinfile:
        path: "{{ zabbix_conf_path }}"
        regexp: '^ServerActive\s*='
        line: "{{ current_serveractive_line.stdout_lines[0] }},{{ new_server_ip }}"
        backrefs: yes

    - name: Display updated configuration
      ansible.windows.win_shell: Get-Content "{{ zabbix_conf_path }}" | Select-String "^Server=|^ServerActive="
      register: updated_config

    - name: Show updated configuration
      ansible.builtin.debug:
        msg: "{{ updated_config.stdout_lines }}"