---
- name: Append new Zabbix server IP to configuration
  hosts: all
  gather_facts: no
  vars:
    zabbix_conf_path: "C:\\Zabbix\\conf\\zabbix_agentd.win.conf"  # Replace with the actual path
    new_server_ip: "10.51.200.123"  # Replace with the new server IP

  tasks:
    - name: Append new IP to Server line
      community.windows.win_lineinfile:
        path: "{{ zabbix_conf_path }}"
        regexp: '^Server='
        line: "Server={{ item }},{{ new_server_ip }}"
        backrefs: yes
      with_items:
        - "{{ lookup('file', zabbix_conf_path) | regex_search('^Server=(.*)$', '\\1') | first }}"

    - name: Append new IP to ServerActive line
      community.windows.win_lineinfile:
        path: "{{ zabbix_conf_path }}"
        regexp: '^ServerActive='
        line: "ServerActive={{ item }},{{ new_server_ip }}"
        backrefs: yes
      with_items:
        - "{{ lookup('file', zabbix_conf_path) | regex_search('^ServerActive=(.*)$', '\\1') | first }}"

    - name: Display updated configuration
      ansible.windows.win_shell: Get-Content "{{ zabbix_conf_path }}" | Select-String "^Server=|^ServerActive="
      register: updated_config

    - name: Show updated configuration
      ansible.builtin.debug:
        msg: "{{ updated_config.stdout_lines }}"