---
- name: Schedule a restart on Windows server
  hosts: windows
  gather_facts: yes
  tasks:

    - name: Create a scheduled task to restart the server
      community.windows.win_scheduled_task:
        name: RestartServer
        description: "Scheduled restart of the Windows server"
        actions:
          - path: C:\Windows\System32\shutdown.exe
            arguments: '/r /t 0'  # /r: restart, /t 0: no delay
        triggers:
          - type: time
            start_boundary: '2024-10-22T11:48:00'  # Set your desired date and time (YYYY-MM-DDTHH:MM:SS)
        username: SYSTEM
        state: present
        enabled: true

    - name: Confirm the scheduled task creation
      community.windows.win_scheduled_task_stat:
        name: RestartServer
      register: task_info

    - name: Display task information
      debug:
        var: task_info