---
- name: Append new Zabbix server IP to configuration
  hosts: all
  gather_facts: no
  vars:
    zabbix_conf_path: "C:\\Zabbix\\conf\\zabbix_agentd.win.conf" # Replace with the actual path
    new_server_ip: "10.51.200.123"  # Replace with the new server IP
    zabbix_service_name: "Zabbix Agent"  # Replace with the actual service name if different

  tasks:
    - name: Stop Zabbix agent service
      ansible.windows.win_service:
        name: "{{ zabbix_service_name }}"
        state: stopped

    - name: Create backup of Zabbix config file
      ansible.windows.win_copy:
        src: "{{ zabbix_conf_path }}"
        dest: "{{ zabbix_conf_path }}.ansible-backup"
        remote_src: yes

    - name: Check if Zabbix config file exists
      ansible.windows.win_stat:
        path: "{{ zabbix_conf_path }}"
      register: config_file

    - name: Read current Server line
      ansible.windows.win_shell: |
        (Get-Content "{{ zabbix_conf_path }}" | Select-String "^Server\s*=").Line -replace '^Server\s*=\s*', ''
      register: current_server_ips
      when: config_file.stat.exists

    - name: Read current ServerActive line
      ansible.windows.win_shell: |
        (Get-Content "{{ zabbix_conf_path }}" | Select-String "^ServerActive\s*=").Line -replace '^ServerActive\s*=\s*', ''
      register: current_serveractive_ips
      when: config_file.stat.exists

    - name: Append new IP to Server line
      community.windows.win_lineinfile:
        path: "{{ zabbix_conf_path }}"
        regexp: '^Server\s*='
        line: "Server={{ current_server_ips.stdout.strip() }},{{ new_server_ip }}"
      when: config_file.stat.exists and current_server_ips.stdout and new_server_ip not in current_server_ips.stdout.split(',')
      register: server_updated

    - name: Append new IP to ServerActive line
      community.windows.win_lineinfile:
        path: "{{ zabbix_conf_path }}"
        regexp: '^ServerActive\s*='
        line: "ServerActive={{ current_serveractive_ips.stdout.strip() }},{{ new_server_ip }}"
      when: config_file.stat.exists and current_serveractive_ips.stdout and new_server_ip not in current_serveractive_ips.stdout.split(',')
      register: serveractive_updated

    - name: Display updated configuration
      ansible.windows.win_shell: Get-Content "{{ zabbix_conf_path }}" | Select-String "^Server=|^ServerActive="
      register: updated_config
      when: config_file.stat.exists and (server_updated.changed or serveractive_updated.changed)

    - name: Show updated configuration
      ansible.builtin.debug:
        msg: "{{ updated_config.stdout_lines }}"
      when: config_file.stat.exists and (server_updated.changed or serveractive_updated.changed)

    - name: Show no changes message
      ansible.builtin.debug:
        msg: "No changes were necessary. The new IP is already present in both Server and ServerActive lines."
      when: config_file.stat.exists and not server_updated.changed and not serveractive_updated.changed

    - name: Show error if config file doesn't exist
      ansible.builtin.debug:
        msg: "Zabbix configuration file not found at {{ zabbix_conf_path }}"
      when: not config_file.stat.exists

    - name: Start Zabbix agent service
      ansible.windows.win_service:
        name: "{{ zabbix_service_name }}"
        state: started